platform: "local"
mode: "train"
keyboard_interrupt_save: false

datasets_targets:
  local: hw_asr.datasets.LibrispeechDataset
  datasphere: hw_asr.datasets.DataSphereLibrispeechDataset

dev_clean:
  _target_: ${datasets_targets[${platform}]}
  part: "dev-clean"
  limit: 10

test:
  _target_: hw_asr.datasets.CustomDirAudioDataset
  audio_dir: "/Users/arturgimranov/CS/fourth_year/dla_course/asr_hw/test_data/audio"
  transcription_dir: "/Users/arturgimranov/CS/fourth_year/dla_course/asr_hw/test_data/transcriptions"

text_encoder:
  _target_: hw_asr.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder
augmentations:
  wave: []
  spectrogram:
    - _target_: hw_asr.augmentations.spectrogram_augmentations.SpecAug
      freq_masks: 2
      time_masks: 5
      freq_width: 27
      time_width: 0.05
data:
  train:
    batch_size: 10
    num_workers: 4
    datasets: 
      - ${dev_clean}
  val: 
    batch_size: 10
    num_workers: 4
    datasets: 
      - ${dev_clean}
preprocessing:
  sr: 16000
  spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    n_mels: 80
  log_spec: true
arch:
  _target_: hw_asr.model.baseline_model.BaselineModel
  n_feats: 80
n_gpu: 1
loss:
  _target_: hw_asr.loss.CTCLoss
metrics:
  shared: 
    - _target_: hw_asr.metric.ArgmaxWERMetric
      name: WER (argmax)
    - _target_: hw_asr.metric.ArgmaxCERMetric
      name: CER (argmax)
  train: []
  evaluation:
    - _target_: hw_asr.metric.BeamSearchWERMetric
      name: WER (beam search)
    - _target_: hw_asr.metric.BeamSearchCERMetric
      name: CER (beam search)
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  steps_per_epoch: ${trainer.len_epoch}
  epochs: ${trainer.epochs}
  anneal_strategy: "cos"
  max_lr: 3e-4
  pct_start: 0.2
trainer:
  epochs: 1
  save_dir: "saved/"
  save_period: 5
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 100
  visualize: "wandb"
  wandb_project: "asr_project"
  len_epoch: 1
  grad_norm_clip: 10
  log_step: 1
  accumulation_steps: 1
resume: null